// Data modified using Notepad++
var data = "AXCXCXCXBYCXCXAZCXAZAZCXCXCXBXCYCXCYCXAZCXCXCXCYCYCYAZCXAYBZBYCXCXAXCXCZCYCYCYCYBXCYAZCYBXAXAXCXCYBXCYCXCXCYAXCYAZAZCYCXAYCYAXCXCZAXAXCYCYCXCYBXCXCYCZAXCXCYCXCXCXCXCYBZCXAYBXCXCYCYCXCYCXCYBXAXBXCYAXCXAXCXCXCYCXCXCXCYCXCXCXCYAXCXAZBXAZCXCXAZCXAZAXCYBXCYBYAZCYAXCXAXCZCYCXAXCYCYAYAXCZCXBZAXCXCXAYAYAXCYBXCYCYCXCYCYCXCXCXCYCYCYCZAXCXCXCXCZCXBXCXCXCXBYBXCXCYCYCZCYCXCYCYCXCXAXCYCXCYCYBYCYCYBXBXBXCZCXAXCXAXCYCZBXBXCXBXCYCXAZCYAXBYCXCYAXCXCYCYCYCYCYAZAZCXCXCYCXCZAXCYCYBXCYCXCXCXBXBXCXCYAYCYCYCYBXBXCXCXAYCXCXCYBXCXCXCXAXBYCZCZBXCXCXCXCYCYCYCYAYBXCXCZCXCYCXCYCYCYCXCXAXAXCYAXAXCXCYBZCZCXCXCXCYBXCYCYCYCXCYCYCXCXCXCZCXCYCYCZAXCXBXCZCYBXCYCZBZAXCXBXAYCYCXCYCYCYCYCXCYAYCYCYCYCZCXCYBZCYCXCXAXCXCYCXBYCYCZCZAXCXAXCYBXCYCYCXCYCXAYCYCYBXCXCYCXCZCYCYCYBYAXCYCZCXCZAZCXCYCXAXCXAYBYAXAXAXCZCZCXCYBXAXAXCYCXCZAZBYBZBYAXBYCXCXCZCXCXCYBXCXCZBXCYCXCXAXCXBYCYBZCYBYCYBYCYBXCXCZCXCYCYCXAXCYCXCXCZCXCYCXCYBYCYCXCYCXCXCXCXBXCZCXCXBXBXAXAZCXCYCXCXCXCYCYCXCXCXAXCXCXCXCXAYCYCXAZCXCYCYCXAXCXCXCYCXCXCYCYBYCYCXAYCXCXCYBYCXCYAXBXCXBYCYCZCZAXCXCXCYBXCYCYCYAZCXCYCXAZCYBYAXCYBXCYBYCXCXCXCYCXBXCXCXAXCYAXCXAZCYCXCYCXCYBYCZCYCZAXCXCXCZCYCXBYAXCYAXBYAXAXBYCXCXCXCYCXBXCYCYCXBXBYBYCYBYAZBZAYCXCXCXBXCXCXCXCYAXCYCYCZBXBYCXCYAXCZCYCZCYAZCZCYBYCYBXCXCYCYAZAYCYCYAYCYCXCYCXCYCYBYCXBXCYAYCYAXCXCYCYBXAXBYCYBZAXCXBYCYCXCYCXCYCYCYBXCYCXCZCZCYCYAYAYCYCXCZBYCYCXAXBXCXCXAYCYCYBYCXBYCXBXCYCZBXAXAYAZCZAXAXCYCYCYAZCYAXCXAYCYAXCXCXCYAXCYCYAZCXCYCXBYCZBXCYAXCYAXBXAXCXCXCXAYAXAZAZAZCXCXCXCXCYAXCYCXBYAZBYCYCYCZCXAXCYBYCXCXAXAXCYCXCZCXAXCXCXBXCYBXCZCXAXAXAZAXAZCYBYBZAXAXCYCZCYCXBYAXAXCXBYBYCYCYBXCXCYCZAXCYCYCXCXCYAZCXCXCYAYCYCZAYCXCYBXBXCYCXCYBYBYCYCYAZAXCXCXCZCZCXCZCYAYAXCXAXCYBYAXCZAYCYCYCYCXCXCXCXCYCXCXCYCYCXBXBXCYCYCXBXAXCXCZAXCXCXCYAZBYCXCXBXCXAXCZCYAXCZCYAXCXCYBXCXBXCXCXCYBZAXCXAXCYCYAXAXAZCXCXCYCXBYCYCYAXCXCXCXCYAYCYCXAZBZCXCXCYCXBYCXAXCYCYAZCYBZCXAXCXCZCXCXCYCYAXCXCZCYCXCYCXCZCXCYCXCXCXAZCYCXCYBZBXCXAXCYCYCXCYCZAYCYBXAXAXBXAYCYBXCYCYCXCYBXCYCXCXCXCXCYCZCXCYCZBXCYCYCXCXAXCYCYBYBYBXAXCXCYAXCYCYCYAXBXCZAZCYCYCZCYCXCZCXAXCXBYAYCXCZAXAXCYCXCXCYAYCYCXAXCXCYCZCZCXBZAXCYCZCXCYCYCXCYCXAYBXAXAXCXCXCYCYCYBXCYCYCYCZAZBYCXCXBXBYCXCYAZCYCXCYCYAXCXCYAYCYCXCXAZCYCXBXAYCYCXCXCXBXAXCXCXCXCXBYAXCYCZCXCXCXCYCXCYBXCXCXCXCXCYCYCXAXCXAZCXBYAZCYCYCZCYBZAZAXAZCXAXCZCZCYCXCYCYCYCXCXCXCXAYCYCXCXCZCYCYBYAXCXCYCXCYBYCXCXBYAXBXCYCXCXCXCXCYCXCYCYAZBXCXCXCXBXCYCXCZBXCYCYCYCXBXCXCYBYCXCXBYAXCXCXAZCZAXAZCYCYAYAXCXCXCZCXCYCYCZCXCXAYCYAYBXCYCYCXCXCYAYCXBYCXCYCXCXAZCYBZCYBXCYCYAXCYCXCXCYCXCYCXCZCXBXCYAXBXCYBXCYAZCYCYCYCYBXCXCXCXCYCYCYCYCXBYCYCXBYBXCXBXCZCZCXCYBXAXCYAXCXCXCXCXCXAZCYAZBXCYCZBXAYCXCXAYCYCYAZAZCYAXCZCXAZCXCZAZCXCXCXCYCYCYCZCYCYCZCXCXAYBYBXCXBXCZBXCYCYCYCXBXAYBYBYCXCXCYCYCYCZCXCXAXBYCYCYCXCXCYCZCZCYCXBXAXCXCZCXBXAXCXCYAZCXCYCYAXCZCXAXCXBXCYCYCYCYAXCYCZBXCZCYBYBYAXCYCXCZCYCXCXCYCYAYCXCYCXCXCYCYCXBXAYCYCXCYCZCYCXCXCXAXCYAXAXCXBYBXBZCYCYCZBXCYCYCXCXAXCXBXCXAXBXAXCXAXCYAXCYCYCYBXBYCXBXCYCXCYCZCXBXCXCYCXCYCXAYCYAZAXCYCYCYCYBYCXCYCYCYCXBXCYAZAYBYCXBYCXBXCXCXBZBYAXAXCYCXCYAXAXCXCYCXCXCZCXCXBXAYCYAXAXBZCYBYAXCXCXCXAZCYBXCXCYCXCYCXBXAYAXCXCYBXCZCXCXCYCXCYAYCYCYAXCXCYCYCYCYAZCYAXCYCYBXAYCYCYCYCXCXAXAXCXAYBXCXCYCYCYCXCYBXAZCYCZAXCXCYCXCYCYCYBXCYCYCXCYCYCYAYAZAZCZCYCXBXCXAXBXAXAXAXBXBYBXCZBYCYBYCXCZBXAXCXBXBXCXAXCYCXCYCXAXCXCXBXCYBXAXAXAZBYAXCYCZCXCYBYAXBXAXCYCXBXCYAZCYCYCXAZAYCYCXAXCXAXCXCYCXCXCXCYCXBXCXCXCXCYAZCYCXCXCYBXCXCXCYCXCXCXAXBXCXCZCYCZCYCYCXCXAZAXCXAXCYCYBXCYCXCXAXCZAYAYCYCXCXCXCYBYCYCYCXCXAYBXCYAYAXBXCYAXCXAXCXCXCXCXAYCYCYAZCXCXAXCYCYCYBXCZCZAXAXAXCXCYCYCXCXCZAXAZCZBXCXCYCYCYCYCXBYCYCXCYCYAXCYCXAXCXCXCXCYCYCYAXCXAXAZBYAXCZCXBXCXAYAZBYAXCXBYBXCXBXAXBYAXCYCXCXCZAXCYAZCYAYCYCYCYCZCYCXCXCXCXAYCYCYCXAZCXBXCYCXCYAZCYCZCZAZCYAXAXCXCXCYAZCYBXCZCYAZCXBZBXCZAXBYCYCYCYBXCYBYAXAZBYBZAYCXCYCYAYBXCZCXCXAZCXCYCYCYBXCXBZAXCYCXCZBXBZCYCZCYAXCXCXAXBXCYCYCYCXCZAYCXCYCXBYCYAYCXAZCXCXCXCXAXAXAYCYCYCXCXCXCXCYBXBXBXAXCXCYCXBXAXCYBYCXCXCXCXCXCXCXCXCXCYCYCXCXCYCYBYCZCYAXBXAXCZCYCXBXAYCYCXAXBXCXCYCYCYAZAZCXCXBZCYCYCYCYCXCXBZCXCXAYAXBYCYCYAXAXAZAZCXBXCZBYCYCYCYCYCYAXBXCYBXCYCZCZBXCXBXCYCXAZBXCZCXCYCXCXCYCYAYAZAXBYCZBXBYCXAYCXCYCXCXCYCYCYAXCYBXCYCYCZBXCXCYCZAXCYCZCYCXCZCXCXCXCYCYCXCXAXAZCYCYAYCXAXCYAZBZCYAXCYCXBYBYAZAXCXCYCZCXAZCYCYBYBXCYCZCYAZCYCYAXCYCYCXCXBXCYCYBYCXCXCYCXCXCYBXCYCZCXAXCXCXCZBZCYAYCYCYCXAXCXBXCXCXCYCXBYBXCXCYCYCXCYCXCYCXCYCXCZAXAXCYCXCXAYCYCXBXCXCXCXCYAYBZCYCZCXAXCXCZCYCYCYCXCXCZCYBZCXCYCXCXCYCYCZCXCZCZCYAXCYAYBXCZCYCYCZCYCYCXCYBXCYCXCXBYAXCYCXCZCXCYCZAXCXAYBXCXCXAZCXCYBYCXCYCYCXBXAYCYCZCYCXCXCXBXBYCXAXCXAXCXBYBXCXCZCYCXBXCYCYCXAZCYCXCYCYCYCYBYCYCXAXCYCYCXBYBZCYCZBXCXAXBYCXCYCYCYAXCZAXCYCYCYCXCXCYAZCYCZCYCYCYCYCXCYBYCYCYBXBXCYCYBZCXBYCXAXAXCXCXBXCXBZCYCYBYCYCXCXAZCXAXCYCXCXBXCYAZCYCYBXAYAXAXCYCYAZCXBXCXBXAZCXCXBZCXCXCXCYAZCYCZCYBYAXCXCYAXAYCXCYCYCXAYCYCXCXCXCYCXAYCXBYBXCXCYBXCXCXCXCXCYBZCYCZCXAXCYBYCYCXCYCZBXCXCYCXCXCXCXAZCYBXCXCYCYCYCYCXAXCXBXCYAXBYAXCZAXCYCXCYCXAXCYCXCYCYBXCZAYCXCXCYCXCYCZCYCXCYAXBXBYCYCXCYCXBYBXCXCZBXCYCXCYAXCYCYCXCYCYCYAYCZCYBYCYCZCZCXCYAXCYCXBYCXCZCZCYCXCXCXAXCYCYCXAXAXAXBXAYAXCXCXAXBYCYCXAZAXCYBYCXCXAYCXCXCZCYCZCYCXBXBXBYCXCYAXAYAXCXBYAXAXBYCXCXBXCXAZCXBXAXCYCXBXAYAXCYCXCXBXCZAXBXCX"

data = data.split("").map((decision) =>
    decision
        .replace("X", "1")
        .replace("Y", "2")
        .replace("Z", "3")
        .replace("A", "1")
        .replace("B", "2")
        .replace("C", "3")
);

// Task 1
var score = 0  
for (var index = 0; index < data.length; index++) {
    if (index % 2 != 0) {
        if (data[index - 1] == data[index]) {
            score += parseInt(data[index]) + 3;
        } else {
            if (data[index] == 3 && data[index - 1] == 1) {
                score += parseInt(data[index]) + 0;
            } else if (data[index] == 1 && data[index - 1] == 3) {
                score += parseInt(data[index]) + 6;
            } else if (data[index - 1] > data[index]) {
                score += parseInt(data[index]) + 0;
            } else {
                score += parseInt(data[index]) + 6;
            }
        }
    }
} 
console.log(score);

// Task 2
score = 0;
for (var index = 0; index < data.length; index++) { 
    var points = 0;
    if (index % 2 != 0) {
        if (data[index] == 2) {
            score += parseInt(data[index - 1]) + 3;
        } else {
            if (data[index] == 3) {
                points = parseInt(data[index - 1]) + 1;
                if (points == 4) {
                    points = 1;
                }
                score += 6 + points;
            }
            if (data[index] == 1) {
                points = parseInt(data[index - 1]) - 1;
                if (points == 0) {
                    points = 3;
                }
                score += points;
            }
        }
    }
}
console.log(score);